
project_id = "ecziljpkvshvapjsxaty"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328

[auth.email]

[edge_runtime]
enabled = true
port = 54329

[functions.ai-agent]
verify_jwt = false

[functions.enhanced-todo-recommendations]
verify_jwt = false

[functions.process-transcript]
verify_jwt = false

[functions.todo-recommendations]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.task-recommendation-agent]
verify_jwt = false

[functions.process-invoice]
verify_jwt = false

[functions.calculate-iol]
verify_jwt = false

[functions.seed-branding-logo]
verify_jwt = false

[functions.meeting-tasks-debug]
verify_jwt = false
